### ISSUE TITLE
avoid panic when number of line exceeds len(plotutil.SoftColors)

### ISSUE THREAD

**Issue by DrGo** [sbinet/covid19#2]
Hi Sebastien,
Thanks for the handy utility.
was wondering if you would consider changing `plotutil.SoftColors[i]` to `plotutil.SoftColors[i%len(plotutil.SoftColors)] ` to avoid out of index panics if more countries (lines) are added to the plot. Different lines may end up with same color. My solution was to copy plotutil.SoftColors to main.go and add additional colors as needed. Another small improvement. 

Best,

/salah

**Comment by sbinet** [comment]
thanks for the report.

**Comment by DrGo** [comment]
any reason for closing with acknowledgement?

**Comment by DrGo** [comment]
sorry did not see the message above. pls ignore
